sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.5"
  - "0.6"
  - "iojs"

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)

notifications:
  email:
    - varun@varungoel.net
    - kavita.anand@optimusinfo.com
    - varun.goel@optimusinfo.com
  slack: optimusinformation:V6INf0bcAimNBTPIQ3lk5tM0
    on_success: always
    on_failure: always
